@echo off
TITLE Nexus Sovereign Zenith - System Boot
COLOR 0A
echo ==================================================
echo      INITIATING NEXUS SOVEREIGN PROTOCOLS...
echo ==================================================
echo.
echo [1/3] Verifying Python Environment...
echo [2/3] Connecting to Local Neural Engine...
echo [3/3] Launching Professional Interface...
echo.
streamlit run app.py
PAUSE
